parameters:
  _param:
    jenkins_cloud_deploy_pipelines:
      # Identity AAA
      - stack_name: aaa_ha_freeipa
        stack_type: heat
        stack_install: core,aaa
        job_timer: ""
        extra_formulas: ""
      - stack_name: k8s_calico
        stack_type: aws
        stack_install: core,k8s,calico
        job_timer: "H H * * *"
#      - stack_name: ceph_ha
#        stack_type: heat
#        stack_install: core
#        job_timer: ""
#      - stack_name: drivetrain_ha
#        stack_type: heat
#        stack_install: core
#        job_timer: ""
#      - stack_name: drivetrain_ha_clusters
#        stack_type: heat
#        stack_install: core
#        job_timer: ""
      - stack_name: k8s_aio_calico
        stack_type: heat
        stack_install: core,k8s,calico
        job_timer: ""
      - stack_name: k8s_aio_contrail
        stack_type: heat
        stack_install: core,k8s,contrail
        job_timer: ""
      - stack_name: k8s_ha_calico
        stack_type: heat
        stack_install: core,k8s,calico
        job_timer: ""
      - stack_name: k8s_ha_contrail
        stack_type: heat
        stack_install: core,k8s,contrail
        job_timer: ""
      - stack_name: os_aio_contrail
        stack_type: heat
        stack_install: core,openstack,contrail
        job_timer: ""
      - stack_name: os_aio_ovs
        stack_type: heat
        stack_install: core,openstack,ovs
        job_timer: ""
      - stack_name: os_ha_contrail
        stack_type: heat
        stack_install: core,openstack,contrail
        job_timer: ""
      - stack_name: os_ha_ovs
        stack_type: heat
        stack_install: core,openstack,ovs
        job_timer: ""
      - stack_name: stacklight_k8s_calico
        stack_type: heat
        stack_install: core,k8s,calico,sl-legacy
        job_timer: ""
      - stack_name: stacklight_os_contrail
        stack_type: heat
        stack_install: core,openstack,contrail,sl-legacy
        job_timer: ""
      - stack_name: stacklight_os_ovs
        stack_type: heat
        stack_install: core,openstack,ovs,sl-legacy
        job_timer: ""
  jenkins:
    client:
      job_template:
        cloud_deploy_heat_template:
          name: deploy-{{stack_type}}-{{stack_name}}
          jobs: ${_param:jenkins_cloud_deploy_pipelines}
          template:
            type: workflow-scm
            discard:
              build:
                keep_num: 20
            concurrent: true
            display_name: "Deploy - {{stack_name}} {{stack_type}}"
            scm:
              type: git
              url: "${_param:jenkins_gerrit_url}/mk/mk-pipelines"
              credentials: "gerrit"
              script: cloud-deploy-pipeline.groovy
            trigger:
              timer:
                spec: "{{job_timer}}"
            param:
              # general parameters
              ASK_ON_ERROR:
                type: boolean
                default: 'false'

              # deployments
              STACK_NAME:
                type: string
                description: Heat stack name. Will be generated if missing.
              STACK_TEMPLATE:
                type: string
                default: "{{stack_name}}"
              STACK_TYPE:
                type: string
                default: "{{stack_type}}"
              STACK_INSTALL:
                type: string
                default: "{{stack_install}}"
              STACK_TEST:
                type: string
                default: ""
              STACK_DELETE:
                type: boolean
                default: 'true'
                description: "Don't enable it if you need to use the lab after"
              STACK_REUSE:
                type: boolean
                default: 'false'
              STACK_COMPUTE_COUNT:
                type: string
                default: '2'

              STACK_TEMPLATE_URL:
                type: string
                default: "${_param:jenkins_gerrit_url}/mk/heat-templates"
              STACK_TEMPLATE_CREDENTIALS:
                type: string
                default: "gerrit"
              STACK_TEMPLATE_BRANCH:
                type: string
                default: "master"
              STACK_CLEANUP_JOB:
                type: string
                default: 'deploy-stack-cleanup'

              # salt master
              SALT_MASTER_CREDENTIALS:
                type: string
                default: "salt-qa-credentials"
              SALT_MASTER_URL:
                type: string
                default: ""
              SALT_OVERRIDES:
                type: text
                default: ""

              # aws api
              AWS_STACK_REGION:
                type: string
                default: "us-west-2"
              AWS_API_CREDENTIALS:
                type: string
                default: "aws-credentials"
              AWS_SSH_KEY:
                type: string
                default: "jenkins-mk"


              # openstack api
              OPENSTACK_API_URL:
                type: string
                default: "https://cloud-cz.bud.mirantis.net:5000"
              OPENSTACK_API_CREDENTIALS:
                type: string
                default: "openstack-devcloud-credentials"
              OPENSTACK_API_PROJECT:
                type: string
                default: "mcp-mk"
              OPENSTACK_API_CLIENT:
                type: string
                default: ""
              OPENSTACK_API_VERSION:
                type: string
                default: "3"
              OPENSTACK_API_PROJECT_DOMAIN:
                type: string
                default: "default"
              OPENSTACK_API_USER_DOMAIN_ID:
                type: string
                default: "default"
              OPENSTACK_API_PROJECT_ID:
                type: string
                default: ""
              OPENSTACK_API_USER_DOMAIN:
                type: string
                default: "default"

              # heat
              HEAT_STACK_ENVIRONMENT:
                type: string
                default: "devcloud"
              HEAT_STACK_ZONE:
                type: string
                default: "mcp-mk"
              HEAT_STACK_PUBLIC_NET:
                type: string
                default: "public"

              # k8s setttings
              K8S_API_SERVER:
                type: string
                default: "http://127.0.0.1:8080"
              K8S_CONFORMANCE_IMAGE:
                type: string
                default: "docker-dev-virtual.docker.mirantis.net/mirantis/kubernetes/k8s-conformance:v1.5.1-3_1482332392819"

              # openstack settings
              TEMPEST_IMAGE:
                type: string
                default: "sandbox-docker-prod-local.docker.mirantis.net/mirantis/rally_tempest:0.1"

