parameters:
  _param:
    jenkins_deploy_lab_mk_jobs: []
  jenkins:
    client:
      job_template:
        deploy_heat_template:
          name: deploy-{{stack_type}}-{{lab}}
          jobs: ${_param:jenkins_deploy_lab_mk_jobs}
          template:
            type: workflow-scm
            discard:
              build:
                keep_num: 20
            concurrent: true
            display_name: "Deploy - {{lab}} {{stack_type}} lab"
            scm:
              type: git
              url: "${_param:jenkins_gerrit_url}/mk/mk-pipelines"
              credentials: "gerrit"
              script: lab-pipeline.groovy
            trigger:
              timer:
                spec: "{{timer}}"
            param:
              # deployments and test settings
              STACK_TYPE:
                type: string
                default: "{{stack_type}}"
              STACK_INSTALL:
                type: string
                default: "{{install}}"
              STACK_TEST:
                type: string
                default: "{{test}}"

              STACK_TEMPLATE_URL:
                type: string
                default: "${_param:jenkins_gerrit_url}/mk/heat-templates"
              STACK_TEMPLATE_CREDENTIALS:
                type: string
                default: "gerrit"
              STACK_TEMPLATE_BRANCH:
                type: string
                default: "master"
              STACK_NAME:
                type: string
                description: Heat stack name. Will be generated if missing.
              STACK_TEMPLATE:
                type: string
                default: "{{lab}}"
              STACK_DELETE:
                type: boolean
                default: 'true'
                description: "Don't enable it if you need to use the lab after"
              STACK_REUSE:
                type: boolean
                default: 'false'
              STACK_CLEANUP_JOB:
                type: string
                default: 'deploy-stack-cleanup'
              # heat
              HEAT_STACK_ENVIRONMENT:
                type: string
                default: "devcloud"
              HEAT_STACK_ZONE:
                type: string
                default: "mcp-mk"
              HEAT_STACK_PUBLIC_NET:
                type: string
                default: "public"

              # salt master
              SALT_MASTER_CREDENTIALS:
                type: string
                default: "salt-qa-credentials"
              SALT_MASTER_URL:
                type: string
                default: ""

              # openstack api
              OPENSTACK_API_URL:
                type: string
                default: "https://cloud-cz.bud.mirantis.net:5000"
              OPENSTACK_API_CREDENTIALS:
                type: string
                default: "openstack-devcloud-credentials"
              OPENSTACK_API_PROJECT:
                type: string
                default: "mcp-mk"
              OPENSTACK_API_CLIENT:
                type: string
                default: ""
              OPENSTACK_API_VERSION:
                type: string
                default: "3"
              OPENSTACK_API_PROJECT_DOMAIN:
                type: string
                default: "default"
              OPENSTACK_API_PROJECT_ID:
                type: string
                default: ""
              OPENSTACK_USER_DOMAIN:
                type: string
                default: "default"
              OPENSTACK_API_USER_DOMAIN:
                type: string
                default: "default"

              # k8s setttings
              K8S_API_SERVER:
                type: string
                default: "http://127.0.0.1:8080"
              K8S_CONFORMANCE_IMAGE:
                type: string
                default: "docker-dev-virtual.docker.mirantis.net/mirantis/kubernetes/k8s-conformance:v1.5.1-3_1482332392819"

              # Tempest settings
              TEMPEST_IMAGE:
                type: string
                description: "Tempest image link"
                default: "sandbox-docker-prod-local.docker.mirantis.net/mirantis/rally_tempest:0.1"
              TARGET_TEST_NODE:
                type: string
                description: "Node to run tests"
                default: ""
              DOCKER_INSTALL:
                type: boolean
                description: "Install docker on the target if true"
                default: "true"
              PATTERN:
                type: string
                description: "Run tests matched to pattern only"
                default: ""

              ASK_ON_ERROR:
                type: boolean
                default: 'false'

