parameters:
  gerrit:
    client:
      project:
        reclass-salt-model:
          enabled: true
          description:
            upstream: git@github.com:Mirantis/ccp-poc-salt-model.git
          access:
            "refs/heads/*":
              actions:
              - name: abandon
                group: ${_param:cluster_name}-core
              - name: create
                group: ${_param:cluster_name}-release
              labels:
              - name: label-Code-Review
                group: ${_param:cluster_name}-core
                score: -2..+2
              - name: label-Workflow
                group: ${_param:cluster_name}-core
                score: -1..+1
            "refs/tags/*":
              actions:
              - name: pushSignedTag
                group: ${_param:cluster_name}-release
          require_change_id: true
          require_agreement: true
          merge_content: true
