parameters:
  salt:
    minion:
      cert:
        k8s_client_prometheus:
          host: ${_param:salt_minion_ca_host}
          authority: ${_param:salt_minion_ca_authority}
          key_file: /srv/volumes/prometheus/kubelet-client.key
          cert_file: /srv/volumes/prometheus/kubelet-client.crt
          common_name: kubelet-client
          signing_policy: cert_client
          alternative_names: IP:${_param:cluster_vip_address},IP:${_param:cluster_node01_address},IP:${_param:cluster_node02_address},IP:${_param:cluster_node03_address},IP:${_param:kubernetes_internal_api_address}
