parameters:
  _param:
    prometheus_server_alert_label_route: email
  prometheus:
    server:
      config:
        alert:
          labels_add:
            route: ${_param:prometheus_server_alert_label_route}
