parameters:
  _param:
    docker_hce_replicas: 1
    docker_image_hce: docker-prod-local.artifactory.mirantis.com/mirantis/oss/hce
    hce_bind_host: hce-api
    hce_bind_port: ${_param:haproxy_hce_bind_port}
    hce_elasticsearch_host: elastic-endpoint-ip
    hce_elasticsearch_port: elastic-endpoint-port
    hce_prometheus_host: prometheus-endpoint-ip
    hce_prometheus_port: prometheus-endpoint-port
    hce_ssl:
      enabled: false
  docker:
    client:
      stack:
        hce:
          environment:
            HCEELASTICHOST: ${_param:hce_elasticsearch_host}
            HCEELASTICPORT: ${_param:hce_elasticsearch_port}
            HCEPROMETHEUSHOST: ${_param:hce_prometheus_host}
            HCEPROMETHEUSPORT: ${_param:hce_prometheus_port}
          service:
            hce-api:
              image: ${_param:docker_image_hce}
              deploy:
                replicas: ${_param:docker_hce_replicas}
                restart_policy:
                  condition: any
              ports:
                - ${_param:haproxy_hce_exposed_port}:${_param:haproxy_hce_bind_port}
          network:
            default:
              external:
                name: oss_backend
