classes:
  - system.docker.client.compose
parameters:
  _param:
    docker_image_jenkins: tcpcloud/jenkins:2.93
    jenkins_master_extra_opts: ""
    jenkins_master_executors_num: 4
    jenkins_master_max_concurent_requests: 40
    jenkins_home_dir_path: /var/jenkins_home
  docker:
    client:
      compose:
        jenkins:
          status: up
          service:
            master:
              environment:
                JENKINS_HOME: ${_param:jenkins_home_dir_path}
                JAVA_OPTS: " -server -XX:+AlwaysPreTouch -Xloggc:${_param:jenkins_home_dir_path}/gc-%t.log -XX:NumberOfGCLogFiles=5 -XX:+UseGCLogFileRotation -XX:GCLogFileSize=20m -XX:+PrintGC -XX:+PrintGCDateStamps -XX:+PrintGCDetails -XX:+PrintHeapAtGC -XX:+PrintGCCause -XX:+PrintTenuringDistribution -XX:+PrintReferenceGC -XX:+PrintAdaptiveSizePolicy -XX:+UseG1GC -XX:+ExplicitGCInvokesConcurrent -XX:+ParallelRefProcEnabled -XX:+UseStringDeduplication -XX:+UnlockExperimentalVMOptions -XX:G1NewSizePercent=20 -XX:+UnlockDiagnosticVMOptions -XX:G1SummarizeRSetStatsPeriod=1 -Djenkins.install.runSetupWizard=false -Dhudson.DNSMultiCast.disabled=true -Dhudson.udp=-1 -Dhudson.footerURL=https://www.mirantis.com ${_param:jenkins_master_extra_opts}"
                JENKINS_NUM_EXECUTORS: ${_param:jenkins_master_executors_num}
                JENKINS_OPTS: " --handlerCountMax=${_param:jenkins_master_max_concurent_requests}"
                https_proxy: ${_param:docker_https_proxy}
                http_proxy: ${_param:docker_http_proxy}
                no_proxy: ${_param:docker_no_proxy}
              image: ${_param:docker_image_jenkins}
              restart: always
              ports:
                - 18081:8080
                - 50001:50000
              volumes:
                - /srv/volumes/jenkins:/var/jenkins_home
                - /etc/ssl/certs/java/cacerts:/etc/ssl/certs/java/cacerts:ro
          network:
            default:
              ipam:
                driver: default
                config:
                  - subnet: 172.29.0.0/24
  linux:
    system:
      directory:
        /srv/volumes/jenkins:
          makedirs: true
          user: 1000
          group: 1000
      package:
        ca-certificates-java:
          version: latest
