parameters:
  docker:
    client:
      service:
        prometheus_pushgateway:
          network: monitoring
          replica: 2
          restart:
            condition: any
          image: ${_param:docker_image_pushgateway}
          ports:
            - 15012:9091
